# Generated by ORMatic

from __future__ import annotations
from sqlalchemy import Column, ForeignKey, Integer, String, Float, Boolean, DateTime, Enum, JSON
from sqlalchemy.orm import relationship, Mapped, mapped_column, DeclarativeBase
from typing_extensions import Optional, List, Type

import ripple_down_rules.datasets


from ormatic.dao import DataAccessObject
from ormatic.custom_types import TypeType

class Base(DeclarativeBase):
    type_mappings = {
        Type: TypeType,
    }


class WorldEntityDAO(Base, DataAccessObject[ripple_down_rules.datasets.WorldEntity]):
    __tablename__ = 'WorldEntityDAO'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)


    polymorphic_type: Mapped[str] = mapped_column(String(255), nullable=False)

    world_id: Mapped[Optional[int]] = mapped_column(ForeignKey('WorldDAO.id', use_alter=True), nullable=True)

    world: Mapped[WorldDAO] = relationship('WorldDAO', uselist=False, foreign_keys=[world_id], post_update=True)

    __mapper_args__ = {
        'polymorphic_on': 'polymorphic_type',
        'polymorphic_identity': 'WorldEntityDAO',
    }

class WorldDAO(Base, DataAccessObject[ripple_down_rules.datasets.World]):
    __tablename__ = 'WorldDAO'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    id: Mapped[int]



    bodies: Mapped[List[BodyDAO]] = relationship('BodyDAO', foreign_keys='[BodyDAO.worlddao_bodies_id]', post_update=True)
    connections: Mapped[List[ConnectionDAO]] = relationship('ConnectionDAO', foreign_keys='[ConnectionDAO.worlddao_connections_id]', post_update=True)
    views: Mapped[List[ViewDAO]] = relationship('ViewDAO', foreign_keys='[ViewDAO.worlddao_views_id]', post_update=True)


class PhysicalObjectDAO(Base, DataAccessObject[ripple_down_rules.datasets.PhysicalObject]):
    __tablename__ = 'PhysicalObjectDAO'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)


    name: Mapped[str] = mapped_column(String(255), nullable=False)
    polymorphic_type: Mapped[str] = mapped_column(String(255), nullable=False)

    physicalobjectdao_contained_objects_id: Mapped[Optional[int]] = mapped_column(ForeignKey('PhysicalObjectDAO.id', use_alter=True), nullable=True)

    contained_objects: Mapped[List[PhysicalObjectDAO]] = relationship('PhysicalObjectDAO', foreign_keys='[PhysicalObjectDAO.physicalobjectdao_contained_objects_id]', post_update=True)

    __mapper_args__ = {
        'polymorphic_on': 'polymorphic_type',
        'polymorphic_identity': 'PhysicalObjectDAO',
    }

class BaseDAO(Base, DataAccessObject[ripple_down_rules.datasets.Base]):
    __tablename__ = 'BaseDAO'

    id: Mapped[int] = mapped_column(Integer, primary_key=True)






class ConnectionDAO(WorldEntityDAO, DataAccessObject[ripple_down_rules.datasets.Connection]):
    __tablename__ = 'ConnectionDAO'

    id: Mapped[int] = mapped_column(ForeignKey(WorldEntityDAO.id), primary_key=True)



    worlddao_connections_id: Mapped[Optional[int]] = mapped_column(ForeignKey('WorldDAO.id', use_alter=True), nullable=True)
    parent_id: Mapped[int] = mapped_column(ForeignKey('BodyDAO.id', use_alter=True), nullable=True)
    child_id: Mapped[int] = mapped_column(ForeignKey('BodyDAO.id', use_alter=True), nullable=True)

    parent: Mapped[BodyDAO] = relationship('BodyDAO', uselist=False, foreign_keys=[parent_id], post_update=True)
    child: Mapped[BodyDAO] = relationship('BodyDAO', uselist=False, foreign_keys=[child_id], post_update=True)

    __mapper_args__ = {
        'polymorphic_identity': 'ConnectionDAO',
        'inherit_condition': id == WorldEntityDAO.id,
    }

class ViewDAO(WorldEntityDAO, DataAccessObject[ripple_down_rules.datasets.View]):
    __tablename__ = 'ViewDAO'

    id: Mapped[int] = mapped_column(ForeignKey(WorldEntityDAO.id), primary_key=True)



    worlddao_views_id: Mapped[Optional[int]] = mapped_column(ForeignKey('WorldDAO.id', use_alter=True), nullable=True)


    __mapper_args__ = {
        'polymorphic_identity': 'ViewDAO',
        'inherit_condition': id == WorldEntityDAO.id,
    }

class BodyDAO(WorldEntityDAO, DataAccessObject[ripple_down_rules.datasets.Body]):
    __tablename__ = 'BodyDAO'

    id: Mapped[int] = mapped_column(ForeignKey(WorldEntityDAO.id), primary_key=True)


    name: Mapped[str] = mapped_column(String(255), nullable=False)

    worlddao_bodies_id: Mapped[Optional[int]] = mapped_column(ForeignKey('WorldDAO.id', use_alter=True), nullable=True)


    __mapper_args__ = {
        'polymorphic_identity': 'BodyDAO',
        'inherit_condition': id == WorldEntityDAO.id,
    }

class PartDAO(PhysicalObjectDAO, DataAccessObject[ripple_down_rules.datasets.Part]):
    __tablename__ = 'PartDAO'

    id: Mapped[int] = mapped_column(ForeignKey(PhysicalObjectDAO.id), primary_key=True)



    robotdao_parts_id: Mapped[Optional[int]] = mapped_column(ForeignKey('RobotDAO.id', use_alter=True), nullable=True)


    __mapper_args__ = {
        'polymorphic_identity': 'PartDAO',
        'inherit_condition': id == PhysicalObjectDAO.id,
    }

class RobotDAO(PhysicalObjectDAO, DataAccessObject[ripple_down_rules.datasets.Robot]):
    __tablename__ = 'RobotDAO'

    id: Mapped[int] = mapped_column(ForeignKey(PhysicalObjectDAO.id), primary_key=True)




    parts: Mapped[List[PartDAO]] = relationship('PartDAO', foreign_keys='[PartDAO.robotdao_parts_id]', post_update=True)

    __mapper_args__ = {
        'polymorphic_identity': 'RobotDAO',
        'inherit_condition': id == PhysicalObjectDAO.id,
    }

class FixedConnectionDAO(ConnectionDAO, DataAccessObject[ripple_down_rules.datasets.FixedConnection]):
    __tablename__ = 'FixedConnectionDAO'

    id: Mapped[int] = mapped_column(ForeignKey(ConnectionDAO.id), primary_key=True)





    __mapper_args__ = {
        'polymorphic_identity': 'FixedConnectionDAO',
        'inherit_condition': id == ConnectionDAO.id,
    }

class PrismaticConnectionDAO(ConnectionDAO, DataAccessObject[ripple_down_rules.datasets.PrismaticConnection]):
    __tablename__ = 'PrismaticConnectionDAO'

    id: Mapped[int] = mapped_column(ForeignKey(ConnectionDAO.id), primary_key=True)





    __mapper_args__ = {
        'polymorphic_identity': 'PrismaticConnectionDAO',
        'inherit_condition': id == ConnectionDAO.id,
    }

class DrawerDAO(ViewDAO, DataAccessObject[ripple_down_rules.datasets.Drawer]):
    __tablename__ = 'DrawerDAO'

    id: Mapped[int] = mapped_column(ForeignKey(ViewDAO.id), primary_key=True)

    correct: Mapped[Optional[bool]]


    handle_id: Mapped[int] = mapped_column(ForeignKey('HandleDAO.id', use_alter=True), nullable=True)
    container_id: Mapped[int] = mapped_column(ForeignKey('ContainerDAO.id', use_alter=True), nullable=True)
    cabinetdao_drawers_id: Mapped[Optional[int]] = mapped_column(ForeignKey('CabinetDAO.id', use_alter=True), nullable=True)

    handle: Mapped[HandleDAO] = relationship('HandleDAO', uselist=False, foreign_keys=[handle_id], post_update=True)
    container: Mapped[ContainerDAO] = relationship('ContainerDAO', uselist=False, foreign_keys=[container_id], post_update=True)

    __mapper_args__ = {
        'polymorphic_identity': 'DrawerDAO',
        'inherit_condition': id == ViewDAO.id,
    }

class CabinetDAO(ViewDAO, DataAccessObject[ripple_down_rules.datasets.Cabinet]):
    __tablename__ = 'CabinetDAO'

    id: Mapped[int] = mapped_column(ForeignKey(ViewDAO.id), primary_key=True)



    container_id: Mapped[int] = mapped_column(ForeignKey('ContainerDAO.id', use_alter=True), nullable=True)

    container: Mapped[ContainerDAO] = relationship('ContainerDAO', uselist=False, foreign_keys=[container_id], post_update=True)
    drawers: Mapped[List[DrawerDAO]] = relationship('DrawerDAO', foreign_keys='[DrawerDAO.cabinetdao_drawers_id]', post_update=True)

    __mapper_args__ = {
        'polymorphic_identity': 'CabinetDAO',
        'inherit_condition': id == ViewDAO.id,
    }

class HandleDAO(BodyDAO, DataAccessObject[ripple_down_rules.datasets.Handle]):
    __tablename__ = 'HandleDAO'

    id: Mapped[int] = mapped_column(ForeignKey(BodyDAO.id), primary_key=True)





    __mapper_args__ = {
        'polymorphic_identity': 'HandleDAO',
        'inherit_condition': id == BodyDAO.id,
    }

class ContainerDAO(BodyDAO, DataAccessObject[ripple_down_rules.datasets.Container]):
    __tablename__ = 'ContainerDAO'

    id: Mapped[int] = mapped_column(ForeignKey(BodyDAO.id), primary_key=True)





    __mapper_args__ = {
        'polymorphic_identity': 'ContainerDAO',
        'inherit_condition': id == BodyDAO.id,
    }

